server.port: 8051

spring:
  application.name: service-trainers
  datasource:
    url: jdbc:postgresql://localhost/service-trainers?useUnicod=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: postgres
    password: ENC(wR1EBiKOVKeYmH8pp4bBTMQEj5Ncm3rj)
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate.ddl-auto: none
  liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml

jasypt:
  encryptor:
    password: dream
